# https://community.traefik.io/t/set-up-paths-in-traefik/2295
# UNTESTED!
---
version: "2"

networks:
  bookstack-front:
    external: true
  bookstack-back:

services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
      - APP_URL=http://localhost/bookstack/
    volumes:
      - /home/user/bookstack/config
    networks:
      - bookstack-front
      - bookstack-back
    restart: unless-stopped
    depends_on:
      - bookstack_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.rule=Host(`localhost`) && PathPrefix(`/bookstack`)"
      - "traefik.http.routers.bookstack.middlewares=bookstack-removeprefix" # Wire middleware to this router
      - "traefik.http.middlewares.bookstack-removeprefix.stripprefix.prefixes=/bookstack"
      - "traefik.http.services.bookstack-svc.loadbalancer.server.port=80" # Because Docker image "linuxserver/bookstack" exposes 2 ports: 80 and 443.
      - "traefik.docker.network=bookstack-front"
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=bookstack
      - TZ=America/New_York
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - /home/user/bookstack/config
    networks:
      - bookstack-back
    restart: unless-stopped
