version: "3"
services:
   gitea:
    image: gitea/gitea:linux-arm64
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - DOMAIN=git.skunkhotel.com
    networks:
      - gitea
      - traefik-public
    deploy:
       labels:
         # Enable and register in traefik
         - traefik.enable=true
         - traefik.docker.network=traefik-public
         - traefik.constraint-label=traefik-public
         # traefikv2
         - traefik.http.routers.gitea.entrypoints=https
         - traefik.http.routers.gitea.rule=Host(`git.skunkhotel.com`)
         - traefik.http.routers.gitea.tls=true
         - traefik.http.services.gitea.loadbalancer.server.port=3000
         - traefik.http.routers.gitea-public-http.rule=Host(`git.skunkhotel.com`)
         - traefik.http.routers.gitea-public-http.entrypoints=https
         - traefik.http.routers.gitea-public-http.middlewares=https-redirect
         # https-redirect middleware to redirect HTTP to HTTPS
         # It can be re-used by other stacks in other Docker Compose files
         - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
         - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
         - traefik.tcp.routers.gitea-ssh.entrypoints=ssh
         - traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc
         - traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22
         - traefik.http.routers.gitea-public-https.tls.certresolver=le
    volumes:
      - /home/gluster/docker-data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
       - db

   db:
     image: postgres:9.6
     restart: on-failure
     environment:
       - POSTGRES_USER=gitea
       - POSTGRES_PASSWORD=gitea
       - POSTGRES_DB=gitea
     networks:
       - gitea
     volumes:
       - /home/gluster/docker-data/gitea:/var/lib/postgresql/data


networks:
  gitea:
    external: false
  traefik-public:
    external: true
